<?php
?>
<script>
     var result= [
        {
            "id": 1210004504,
            "customerNumber": "1-65",
            "firstName": "Nurija",
            "lastName": "Schmitt",
            "dateOfBirth": "1960-03-05",
            "email": null,
            "gender": "UNISEX",
            "street": "Eilenau",
            "houseNumber": "22",
            "zipCode": "22087",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "10065"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Nurija Schmitt",
                "bankName": "Postbank Ndl der DB Privat- und Firmenkundenbank",
                "bic": "PBNKDEFFXXX",
                "iban": "DE02100100100006820101"
            }
        },
        {
            "id": 1210006217,
            "customerNumber": "1-258",
            "firstName": "Alessio",
            "lastName": "Albrecht",
            "dateOfBirth": "1960-09-14",
            "email": null,
            "gender": "MALE",
            "street": "Sylvesterallee",
            "houseNumber": "16",
            "zipCode": "22525",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "10258"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Alessio Albrecht",
                "bankName": "Hamburger Sparkasse",
                "bic": "HASPDEHHXXX",
                "iban": "DE02200505501015871393"
            }
        },
        {
            "id": 1210019670,
            "customerNumber": "1-272",
            "firstName": "Patricia",
            "lastName": "Imelda",
            "dateOfBirth": "1954-01-15",
            "email": "dmytro.kononiuk+test1@egym.com",
            "gender": "FEMALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "UA",
            "status": "MEMBER",
            "cardNumbers": [
                "098766"
            ],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210033330,
            "customerNumber": "1-291",
            "firstName": "Simon",
            "lastName": "Test-Member",
            "dateOfBirth": "1989-03-01",
            "email": "simontestml1@egym.com",
            "gender": "MALE",
            "street": "Teststraße",
            "houseNumber": "111",
            "zipCode": "89000",
            "city": "München",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/a7fa08de-0e47-4432-b580-ee9516091140.jpg?Expires=1683622800&Signature=LV2UkdXKaUS6U~tEl5F4z81LJWa7U1zsJCkPEWsh9FhkLfKCskNFAaPmFxvZWV8-IS9aHZwv4bYbX5iQl7oOvGaAxlMPgdRwGiKg3JmkToyKzSG79RI0ZepdLyH3sJFN4R6vzzpJOABH4OTkrWbgM~I5ffp4DthfYBWUBngUxFcxiSvUVGOnWWqvW0vHwWyflUl4cnsBlcmH~OPMohCJbzYpu094po7gCwahEdmD1I-SA~W30rzvRn1K~KSWMFo5XOAP3eClDu2El8gdUNIo9PXLZTnCHy~fpIaWjSfzBNKhEXLjq2iTtx7DJjGYsYEiWSFVV5Tt9r4~LUmBwd8xeQ__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210039010,
            "customerNumber": "1-297",
            "firstName": "Simon",
            "lastName": "Test-Prospect2",
            "dateOfBirth": "2000-06-01",
            "email": "simontestprospect2ml@egym.com",
            "gender": "MALE",
            "street": "Prospect Street",
            "houseNumber": "3",
            "zipCode": "88888",
            "city": "Pro City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210044210,
            "customerNumber": "1-302",
            "firstName": "OpenAPI",
            "lastName": "E2E",
            "dateOfBirth": "2004-06-02",
            "email": "open-api-demo@magilcine.com",
            "gender": "UNISEX",
            "street": "Street",
            "houseNumber": "1",
            "zipCode": "ZIP",
            "city": "City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "oisdf097q345542"
            ],
            "imageUrl": null,
            "phonePrivate": "123456789",
            "phonePrivateMobile": "987654321",
            "phoneBusiness": "56748392",
            "phoneBusinessMobile": "109258674",
            "bankAccount": null
        },
        {
            "id": 1210129370,
            "customerNumber": "1-324",
            "firstName": "Open",
            "lastName": "API Basic",
            "dateOfBirth": "2001-08-01",
            "email": "openapidemo@magicline.com",
            "gender": "MALE",
            "street": "Example",
            "houseNumber": "1",
            "zipCode": "232-11",
            "city": "Example City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1209u312h3u912j"
            ],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/291567a5-4602-48e9-a923-42791ff38643.jpg?Expires=1683622800&Signature=MrYBl8wB6vLGlwfF8IAYmnByc6oEk0msxwtW~PZgWa9VwjHT6wAjMjgaaAiRAlG9YzTAHQvZuBMk4r3nuGB2-~4B5-YDlfYOd~GB2rWfwHetskdmk8hLFgD05wdnWVqJ5MYpoxpKJPJo05fvkJaKNN2JpwROYuXdUHXro5R0S59anmzJ75rr5pW1kKkYC8D7KnAPAZtIbzntZGrPF~Oj5iGENhR4-b4vzIGc7pcFDURudpaKcmtHk1TtDa7-UcP5N2-atBXFjzhTeOZb4NobC~xg0SFai~Xl0j8y4bKtYOa~UJlhE7xeLHAjbB3bt-I8Jw7WpTbHTrCMEOiYzO4JGA__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "777666555",
            "phonePrivateMobile": "888777666",
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210133970,
            "customerNumber": "1-325",
            "firstName": "Open",
            "lastName": "API Premiums",
            "dateOfBirth": "2001-08-01",
            "email": "openapidemo@magicline.com",
            "gender": "MALE",
            "street": "Example",
            "houseNumber": "1",
            "zipCode": "232-11",
            "city": "Example City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "joasd9h23891"
            ],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/340f275f-5683-4527-8088-df056470d627.jpg?Expires=1683622800&Signature=Qo-GI9hzGtU835fxWBydoLrcbVprotU0v3mxy8e3ktT7ZfW7EflseqNAn8zQHf9CKQEya8pKXt0nt24ltwUZNcGiiE8aNyM4gsnjmfFKTa9yc0pAXYZCeBMNujc4efClwxq73ePrJZoarERAG9ZkdVKjLCxDp-r44amSMAICfwNH5HsAmfTMM6UzfHyMI-dl2tJ1ZjJopcUyhDbmujxBwGBJTWSgqNT1Z8t83qm1iYf3xjCt9nJFpfx7Xups4B1NMJCVf07aA0YxRrvKsWbvMdc8794NrLYGJSEjkali9ZRqlR3z8Qj1AQEQFPP3ZQQDI1Ddj2hvYM3K3lKk3iWCmg__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "999888777",
            "phonePrivateMobile": "888777666",
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210138450,
            "customerNumber": "1-326",
            "firstName": "Simon1",
            "lastName": "Test-Member2",
            "dateOfBirth": "1989-03-01",
            "email": "simontestml2@egym.com",
            "gender": "MALE",
            "street": "Teststreet",
            "houseNumber": "1",
            "zipCode": "10000",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210154280,
            "customerNumber": "1-328",
            "firstName": "Simon",
            "lastName": "Test-ManagedAccount",
            "dateOfBirth": "1989-03-01",
            "email": "testmanagedaccountegym@gmx.de",
            "gender": "MALE",
            "street": "Teststreet",
            "houseNumber": "1",
            "zipCode": "12345",
            "city": "Aachen",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210167230,
            "customerNumber": "1-329",
            "firstName": "HB",
            "lastName": "Test",
            "dateOfBirth": "1970-02-01",
            "email": "magicline@byom.de",
            "gender": "MALE",
            "street": "Hauptstr",
            "houseNumber": "133",
            "zipCode": "80000",
            "city": "Musterstadt",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/007a1355-0b10-464f-b16c-887cc6a47856.jpg?Expires=1683622800&Signature=cJb6ag2QWmmd0yuqV~bDM5kDKbDhtnFV7fpTnY4jfEx60NQESzIAPxcUFy9CzMjcm08qpWqXSrORTJEc~IgOUJx2nqKdgIwKqKGvDks4sODyOODe1eb22TPiS210DpAjhpYJl09dpeqrmgQDqAhXCHUDKkjidon0f13RtSASKi81TDCzjKM7w2eKkOwJhx0KmRaqajh9ct6Su2Rnm5lJhdlBxSRf6U05kT~DKN7qO0C3H0VAK-MNtYnGf9sh-GftoSn4UeOtV~xKhJ0jYr~lXKxXbHURLIVTfkAgWouNyNW7oTtdEFQejRYriDd6hCuSLwQrVuQyFBSXB5u91CyqBA__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "089123456",
            "phonePrivateMobile": "017512345",
            "phoneBusiness": "089145566",
            "phoneBusinessMobile": "017866988",
            "bankAccount": null
        },
        {
            "id": 1210190341,
            "customerNumber": "1-331",
            "firstName": "Nicolas",
            "lastName": "Festl",
            "dateOfBirth": "1981-01-01",
            "email": "nftest@mailinator.com",
            "gender": "MALE",
            "street": "Test",
            "houseNumber": null,
            "zipCode": "1234",
            "city": "Mun",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1234567"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210220692,
            "customerNumber": "1-332",
            "firstName": "Test36",
            "lastName": "Dmytro",
            "dateOfBirth": "1990-11-09",
            "email": "dmytro.kononiuk+mltest36@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/0511d9ef-4e5a-4b09-bc0d-02c98307a23c.jpg?Expires=1683622800&Signature=B137BCUmTPuegWW1FSFEbfvLF9of73qe3WadLQHFs0yMH5YNNbKGT03-rV78yAc22AlLzZIfRe3vSo4GAob0tbjKpwIf-98TscWhMkD9MdI9Wknr2jR1XQ96dS2YQ1T4QiPkAECh0zCrPU2RXswJNwZ~eAI8KGFAGE4Xy4EXRcLegD20MUqlC8uSnHZdN5sEvnvDWnXg0cuAKzKR80L0WIDMHhilPncEtfy9vVxVXMqmaUVJCZu09JsAi21q07hwYyPAE-~tt6Yis8YXqi9V9JRv109cLLT0h6jize67AwQr-T3fsNmV-2xAL250eOmReN2KrCKPl8B7sFlWwf74Rw__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210224970,
            "customerNumber": "1-334",
            "firstName": "John",
            "lastName": "Doe",
            "dateOfBirth": "2000-01-01",
            "email": "test@example.com",
            "gender": "MALE",
            "street": "Am Bahnhof",
            "houseNumber": "1",
            "zipCode": "11111",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "123145551"
            ],
            "imageUrl": null,
            "phonePrivate": "+1 555 1234",
            "phonePrivateMobile": "+1 555 1235",
            "phoneBusiness": "+1 555 1236",
            "phoneBusinessMobile": "+1 555 1237",
            "bankAccount": null
        },
        {
            "id": 1210230510,
            "customerNumber": "1-337",
            "firstName": "John",
            "lastName": "Doe",
            "dateOfBirth": "2000-01-01",
            "email": "test@example.com",
            "gender": "MALE",
            "street": "Am Bahnhof",
            "houseNumber": "1",
            "zipCode": "11111",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "+1 555 1234",
            "phonePrivateMobile": "+1 555 1235",
            "phoneBusiness": "+1 555 1236",
            "phoneBusinessMobile": "+1 555 1237",
            "bankAccount": null
        },
        {
            "id": 1210237110,
            "customerNumber": "1-339",
            "firstName": "prope",
            "lastName": "test",
            "dateOfBirth": null,
            "email": null,
            "gender": "MALE",
            "street": null,
            "houseNumber": null,
            "zipCode": null,
            "city": null,
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "3251417183"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210262621,
            "customerNumber": "1-355",
            "firstName": "seca",
            "lastName": "test",
            "dateOfBirth": "1985-11-25",
            "email": null,
            "gender": "UNISEX",
            "street": "Hammer Steindamm",
            "houseNumber": null,
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4712"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210262930,
            "customerNumber": "1-353",
            "firstName": "Thies",
            "lastName": "Bruhn",
            "dateOfBirth": "1985-11-25",
            "email": null,
            "gender": "MALE",
            "street": "Hammer Steindamm",
            "houseNumber": null,
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4711"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210273101,
            "customerNumber": "1-359",
            "firstName": "test2",
            "lastName": "seca",
            "dateOfBirth": "1984-11-14",
            "email": null,
            "gender": "MALE",
            "street": "Hammer Steindamm 3-25",
            "houseNumber": null,
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4713"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210274071,
            "customerNumber": "1-361",
            "firstName": "Marie",
            "lastName": "seca",
            "dateOfBirth": "1980-07-16",
            "email": null,
            "gender": "FEMALE",
            "street": "Hammer Steindamm 3-25",
            "houseNumber": null,
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4714"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210275140,
            "customerNumber": "1-363",
            "firstName": "Melanie",
            "lastName": "seca",
            "dateOfBirth": "1981-10-29",
            "email": null,
            "gender": "FEMALE",
            "street": "Hammer Steindamm 3-25",
            "houseNumber": null,
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4715"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210297171,
            "customerNumber": "1-365",
            "firstName": "Ana",
            "lastName": "seca",
            "dateOfBirth": "1966-11-09",
            "email": null,
            "gender": "FEMALE",
            "street": "Hammer Steindamm",
            "houseNumber": "3",
            "zipCode": "22089",
            "city": "22089",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1966"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210297340,
            "customerNumber": "1-364",
            "firstName": "Thies",
            "lastName": "Magicline",
            "dateOfBirth": "1984-09-21",
            "email": "richard.mietz@seca.com",
            "gender": "MALE",
            "street": "Dudenweg",
            "houseNumber": "10b",
            "zipCode": "22117",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "2511"
            ],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/7d7d7961-0995-4498-a337-b76e56292d7b.jpg?Expires=1683622800&Signature=NMCn4xtz20gZj223P89OUx3k~oC6PCijPVaAEtF5Lrn4kbWNfN7mFe1-lxcJQtCEVFmZS~qmw6BVfiQex8sMgka6OQifko1lAehtkeJTkAEuCPaAor7HZRv1WDgD8O2GzaD5wu-A~2PaxHl~CTcHiNVt1IwBJhO26Y6pTAs5HhwpLL1Hi75TSeD-2xtTSkRnF5o5VjBi-v4a7ku7T1G~2Zw6mber5nAlief3yGjru13pYsz3rmmgldg8QBROkjw8U30zieAHLwqeu1E9rBxiXImuMwT6RmKhvftY-Ke4ApxBjNHutm8kb5F2v~yPhncK4rB84RDwnRVKxkkyuG1fcg__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210297681,
            "customerNumber": "1-366",
            "firstName": "Patricia",
            "lastName": "seca",
            "dateOfBirth": "1991-08-31",
            "email": null,
            "gender": "FEMALE",
            "street": "Hammer Steindamm",
            "houseNumber": "3",
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1991"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210382640,
            "customerNumber": "1-367",
            "firstName": "Jane",
            "lastName": "Doe",
            "dateOfBirth": "2000-01-01",
            "email": "test@example.com",
            "gender": "MALE",
            "street": "Am Bahnhof",
            "houseNumber": "1",
            "zipCode": "11111",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "05040608"
            ],
            "imageUrl": null,
            "phonePrivate": "+1 555 1234",
            "phonePrivateMobile": "+1 555 1235",
            "phoneBusiness": "+1 555 1236",
            "phoneBusinessMobile": "+1 555 1237",
            "bankAccount": null
        },
        {
            "id": 1210383680,
            "customerNumber": "1-368",
            "firstName": "Testerich_2",
            "lastName": "Testerino_2",
            "dateOfBirth": "2001-12-01",
            "email": null,
            "gender": "MALE",
            "street": "teststr.",
            "houseNumber": "1",
            "zipCode": "12345",
            "city": "Test",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210411650,
            "customerNumber": "1-369",
            "firstName": "Test",
            "lastName": "ML Product",
            "dateOfBirth": "1989-03-01",
            "email": "testegymplusml@egym.com",
            "gender": "MALE",
            "street": "Teststreet",
            "houseNumber": "1",
            "zipCode": "12345",
            "city": "EGYM",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1234563456"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210426060,
            "customerNumber": "1-370",
            "firstName": "Milon",
            "lastName": "Honk",
            "dateOfBirth": "2023-01-24",
            "email": null,
            "gender": "UNISEX",
            "street": "Im Mittleren Gras",
            "houseNumber": "21",
            "zipCode": "86152",
            "city": "Augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1123581321"
            ],
            "imageUrl": null,
            "phonePrivate": "012345-44333344345263345",
            "phonePrivateMobile": "111111111",
            "phoneBusiness": "2222112121",
            "phoneBusinessMobile": "54566754",
            "bankAccount": null
        },
        {
            "id": 1210426590,
            "customerNumber": "1-371",
            "firstName": "sdfsadf",
            "lastName": "afsdasdf",
            "dateOfBirth": "1999-11-11",
            "email": null,
            "gender": "MALE",
            "street": "Hauptstraße",
            "houseNumber": "5",
            "zipCode": "86154",
            "city": "Augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "456789321"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210428830,
            "customerNumber": "1-372",
            "firstName": "Tetiana",
            "lastName": "Test",
            "dateOfBirth": "1990-01-12",
            "email": "test_ml_updated@mailinator.com",
            "gender": "FEMALE",
            "street": "test",
            "houseNumber": "test",
            "zipCode": "897987nhfghjgfhjghjghjghj",
            "city": "test",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "123123",
            "phonePrivateMobile": "3123123",
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Test",
                "bankName": "Postbank Ndl der Deutsche Bank",
                "bic": "PBNKDEFFXXX",
                "iban": "DE02100100100006820101"
            }
        },
        {
            "id": 1210433500,
            "customerNumber": "1-373",
            "firstName": "Product",
            "lastName": "TestML",
            "dateOfBirth": "1990-01-04",
            "email": "testmlproduct@egym.com",
            "gender": "FEMALE",
            "street": null,
            "houseNumber": null,
            "zipCode": null,
            "city": null,
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210435670,
            "customerNumber": "1-374",
            "firstName": "Test",
            "lastName": "AryML",
            "dateOfBirth": "1975-08-01",
            "email": "aryml@egym.com",
            "gender": "FEMALE",
            "street": "TestStreet",
            "houseNumber": "1",
            "zipCode": "44765",
            "city": "TestCity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/9faa0c8c-4ab7-4d77-bb86-73902e9ed894.jpg?Expires=1683622800&Signature=SvAhsz4Pf1F75GL02p7q0dKIoOBiPKtiSfFljtnxgwvdN35mmyXcQV2Gl9Xe8qZ6Jp2pHFmPjx7Kz1Ik7Qnd6xCjX3d2MmUghszdrLHlV4X5VWNd3o4x7vgpqTUzS2CIlafbmABP0LQz5SQrKpL8sHzt7m5c-PaGapqNEpEdqI4T8CxsK3ccKlwM3XsWgY9LgROPdjKdeCgnN0-gChFhE5detgsxhje4ZpJCR5pO645~ogHqr4JWfteBcnnD5w5UM315RmFNrgYwOOrfFACJ4jOqG2J5QJghdOH6XjXW4hgiW6BC7BHNWuohpKm~~vxaRuURUK6AcGJw6~4jt4aKtw__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210435990,
            "customerNumber": "1-375",
            "firstName": "Dmytro",
            "lastName": "Test37",
            "dateOfBirth": "2001-01-11",
            "email": "dmytro.kononiuk+mltest37@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/842ce3a0-072b-4758-b627-b43c89431a30.jpg?Expires=1683622800&Signature=jroJHxrw86V~nitaBcjHZSfjN~E7t1iLj3KHbDCUvCPf7saseWq8XCYO9TkxRptR7D2bKHlfvtmCncS5RE7DfeoLBSNXNCcM9d~WfWQMo4fLAOCEJ5pEIHh5ELTtWg7ura8Giq-ty5ASHzo9EXjCTtW~yLEQ3twbhFrxO1qWtnOMTvF8yA1myIk94ErF3ES4I9~x~ys7LR6FGa5iZFlF6PqPPawP~RS4AaqODycps54AFWVLb5qS5Himxe-5srlLBQPvPkw-eixrYtaEKhGFzkhfR06f~F2i5OMy4NaoRrDGAKuNXe926ybV1dUzjIPFefekSBUxosLKYA0b2w7lyw__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210440210,
            "customerNumber": "1-376",
            "firstName": "Tetianatest",
            "lastName": "Tetiana",
            "dateOfBirth": "2010-01-24",
            "email": "hgfhfgjhdfhdfhfdgfjgfhfgh@rtewtwe.com",
            "gender": "FEMALE",
            "street": "hjvр",
            "houseNumber": "7440",
            "zipCode": "63753",
            "city": "gv",
            "country": "UA",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "36",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Tetianata Tetianakk",
                "bankName": "Deutsche Kreditbank Berlin",
                "bic": "BYLADEM1001",
                "iban": "DE02120300000000202051"
            }
        },
        {
            "id": 1210447593,
            "customerNumber": "1-381",
            "firstName": "testml",
            "lastName": "Test",
            "dateOfBirth": "2000-09-08",
            "email": "mltest@egym.com",
            "gender": "UNISEX",
            "street": "Strasse",
            "houseNumber": "3",
            "zipCode": "45678",
            "city": "Stadt",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210447760,
            "customerNumber": "1-377",
            "firstName": "AryPL",
            "lastName": "TestML",
            "dateOfBirth": "1999-01-15",
            "email": "testpdml@egym.com",
            "gender": "FEMALE",
            "street": "Teststreet",
            "houseNumber": "2",
            "zipCode": "345637",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210449690,
            "customerNumber": "1-378",
            "firstName": "Ary",
            "lastName": "ProductML",
            "dateOfBirth": "2001-01-18",
            "email": "testary@egym.com",
            "gender": "FEMALE",
            "street": "TestStreet",
            "houseNumber": "2",
            "zipCode": "56489",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210450030,
            "customerNumber": "1-379",
            "firstName": "Test",
            "lastName": "Addon",
            "dateOfBirth": "1998-01-16",
            "email": "addon@egym.com",
            "gender": "MALE",
            "street": "Streettest",
            "houseNumber": "1",
            "zipCode": "67897",
            "city": "Citytest",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210450031,
            "customerNumber": "1-380",
            "firstName": "Addon",
            "lastName": "TestCancel",
            "dateOfBirth": "2002-01-18",
            "email": "cancel@egym.com",
            "gender": "FEMALE",
            "street": "TestStreet",
            "houseNumber": "5",
            "zipCode": "45689",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210450910,
            "customerNumber": "1-382",
            "firstName": "productML",
            "lastName": "prospect",
            "dateOfBirth": "2000-01-16",
            "email": "prospectproduct@egym.com",
            "gender": "MALE",
            "street": "prospectstreet",
            "houseNumber": "2",
            "zipCode": "6786",
            "city": "prospectcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210451780,
            "customerNumber": "1-383",
            "firstName": "Cancel",
            "lastName": "AryML",
            "dateOfBirth": "1989-01-31",
            "email": "productcancel@egym.com",
            "gender": "MALE",
            "street": "Teststr",
            "houseNumber": "1",
            "zipCode": "89761",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210451782,
            "customerNumber": "1-385",
            "firstName": "Dmytro",
            "lastName": "Test38",
            "dateOfBirth": "2000-05-05",
            "email": "dmytro.kononiuk+mltest38@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Dmytro Test38",
                "bankName": "BARCLAYS BANK UK PLC",
                "bic": "BUKBGB22XXX",
                "iban": "GB33BUKB20201555555555"
            }
        },
        {
            "id": 1210452980,
            "customerNumber": "1-384",
            "firstName": "Product",
            "lastName": "Future",
            "dateOfBirth": "1987-04-17",
            "email": "future@egym.com",
            "gender": "FEMALE",
            "street": "TestStr.",
            "houseNumber": "1",
            "zipCode": "7896",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210452981,
            "customerNumber": "1-386",
            "firstName": "Dmytro",
            "lastName": "Test39",
            "dateOfBirth": "2000-01-04",
            "email": "dmytro.kononiuk+mltest39@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210456330,
            "customerNumber": "1-387",
            "firstName": "Max",
            "lastName": "Mustermann",
            "dateOfBirth": "1997-01-24",
            "email": "Musterremove@egym.com",
            "gender": "MALE",
            "street": "Musterstr",
            "houseNumber": "1",
            "zipCode": "67499",
            "city": "Mustercity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210464440,
            "customerNumber": "1-389",
            "firstName": "Member",
            "lastName": "Cool",
            "dateOfBirth": "1993-01-13",
            "email": "citymore@gmail.com",
            "gender": "MALE",
            "street": "Stretty Street",
            "houseNumber": "123",
            "zipCode": "1882",
            "city": "Citymore",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "151615161516"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210467170,
            "customerNumber": "1-391",
            "firstName": "test",
            "lastName": "Ary1",
            "dateOfBirth": "1987-02-28",
            "email": "connecttestary@egym.com",
            "gender": "FEMALE",
            "street": "Arystr",
            "houseNumber": "1",
            "zipCode": "89786",
            "city": "Arycity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210468350,
            "customerNumber": "1-392",
            "firstName": "Lon",
            "lastName": "Mi",
            "dateOfBirth": "1995-01-05",
            "email": null,
            "gender": "MALE",
            "street": "Strasse",
            "houseNumber": "14",
            "zipCode": "12231",
            "city": "Stadt",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "85859565"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210470161,
            "customerNumber": "1-397",
            "firstName": "milon",
            "lastName": "Test6",
            "dateOfBirth": "1999-11-11",
            "email": null,
            "gender": "MALE",
            "street": "csggf",
            "houseNumber": null,
            "zipCode": "5656",
            "city": "fgggdf",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "95876"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210470162,
            "customerNumber": "1-398",
            "firstName": "Connect",
            "lastName": "Test1",
            "dateOfBirth": "1989-06-04",
            "email": null,
            "gender": "MALE",
            "street": "strrr",
            "houseNumber": "678 gg",
            "zipCode": "34345",
            "city": "cvdccd",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "3456",
            "phonePrivateMobile": "87988",
            "phoneBusiness": "1",
            "phoneBusinessMobile": "21",
            "bankAccount": null
        },
        {
            "id": 1210470320,
            "customerNumber": "1-393",
            "firstName": "Test2",
            "lastName": "Milon",
            "dateOfBirth": "2001-01-25",
            "email": "meixner@milon.com",
            "gender": "MALE",
            "street": "Str",
            "houseNumber": null,
            "zipCode": "1",
            "city": "C",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "56789"
            ],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/bcfb79a7-b512-4b54-b511-c285e831253f.jpg?Expires=1683622800&Signature=hxYhxFdmNAh4HmruXVcacQpZuskDID2PlKbeRW9OLb5P72jHgAaKSE8WzPivpnXsaloQqyFWTyehCSsvdr10tDorAtohJiZeLqBK8IuG8aYvlw~rSeNG1KCRezk9lZmTS8ZK~5Ri1Rd9txWwMDSsUf1YvSYxKpeE8Xf5tg0klbHJilRbTGk~~2wtSBL~UNpPdrLMAao~3I9miFpe1cwEakwwqT4GP6zQ1t7kvCRO5scjbJDGWTRqsLRspiHhhFfSh93DSk7LtDkYTqU2NkcGVTBxf4Ls-4CtiJUsRAa7WBiw9g2fGqiNVBXARhsqRobv22Ca6Si6clmHxeiphGZPvg__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210471250,
            "customerNumber": "1-394",
            "firstName": "Milon",
            "lastName": "Image",
            "dateOfBirth": "1999-11-11",
            "email": "test3@example.com",
            "gender": "MALE",
            "street": "mystreet",
            "houseNumber": "67 h",
            "zipCode": "334",
            "city": "mycity",
            "country": "GM",
            "status": "MEMBER",
            "cardNumbers": [
                "MilonIstToll"
            ],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/f3923889-4354-4931-8625-0a397b89ebc0.jpg?Expires=1683622800&Signature=hJgNhu2B-VnjT6AptHCjRzr31jQcdWeiKZl2dJKRGe9j9jhzmNL1dFjBgsoMuFo2HD59uT2GdV0Nns4laHTl6zo7CAmDDDEXwNIGhg5VXPTKKaKdxokBLUTwNtwfKL3SiSq~Sg9xKdCjBlEsaTf25C7I~23T9kTGRDjyrr8oxG8YdqLkvs9Lt-ufU7EbHgTrjVwUmB0SkE2oGFrF2EWlfPxHqlQvqOHe0VcWXylJ~JqlevlGylKkxHsb1-J5DgmsizOvY9wCsynzi75aQEdU9ufRlTWFO5E0X5bKwopy5UySvXt0QsUpjwS~uJDIPb9gge-o5qGFU7R-p0Nmk47m-w__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "88888",
            "phonePrivateMobile": "77777",
            "phoneBusiness": "66666",
            "phoneBusinessMobile": "55555",
            "bankAccount": null
        },
        {
            "id": 1210471251,
            "customerNumber": "1-395",
            "firstName": "Milon",
            "lastName": "Test4",
            "dateOfBirth": "1999-11-11",
            "email": null,
            "gender": "FEMALE",
            "street": "xdsdssd",
            "houseNumber": null,
            "zipCode": "67890",
            "city": "sss",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "87890"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210471850,
            "customerNumber": "1-396",
            "firstName": "Milon",
            "lastName": "Test5",
            "dateOfBirth": "1999-11-11",
            "email": null,
            "gender": "UNISEX",
            "street": "kjg",
            "houseNumber": null,
            "zipCode": "767",
            "city": "bvn",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210473320,
            "customerNumber": "1-399",
            "firstName": "Test",
            "lastName": "FutureML",
            "dateOfBirth": "1978-01-01",
            "email": "futuretest@egym.com",
            "gender": "FEMALE",
            "street": "Futurestreet",
            "houseNumber": "1",
            "zipCode": "76893",
            "city": "Futurecity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210473321,
            "customerNumber": "1-400",
            "firstName": "test",
            "lastName": "Basic",
            "dateOfBirth": "1989-11-01",
            "email": "basicmail@egym.com",
            "gender": "UNISEX",
            "street": "Basicstr",
            "houseNumber": "1",
            "zipCode": "89765",
            "city": "BAsiccity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210475391,
            "customerNumber": "1-402",
            "firstName": "Test201456",
            "lastName": "Milon",
            "dateOfBirth": "2023-01-27",
            "email": null,
            "gender": "FEMALE",
            "street": "Am Mittleren Moos",
            "houseNumber": "53",
            "zipCode": "86186",
            "city": "Augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1385468283"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210475690,
            "customerNumber": "1-401",
            "firstName": "JenniTest",
            "lastName": "JenniTest",
            "dateOfBirth": "1982-01-12",
            "email": "Jennifer.Pozduga+test@egym.com",
            "gender": "FEMALE",
            "street": "Teststrasse",
            "houseNumber": "8",
            "zipCode": "81373",
            "city": "München",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210477630,
            "customerNumber": "1-403",
            "firstName": "milon",
            "lastName": "test7",
            "dateOfBirth": "2023-01-17",
            "email": null,
            "gender": "FEMALE",
            "street": "adfgds",
            "houseNumber": null,
            "zipCode": "f4444",
            "city": "dcsvfs",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "4321"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210477842,
            "customerNumber": "1-408",
            "firstName": "test14",
            "lastName": "milon",
            "dateOfBirth": "2001-12-13",
            "email": "test@example.com",
            "gender": "MALE",
            "street": "streetstr",
            "houseNumber": null,
            "zipCode": "76fdgt5",
            "city": "lgkjmgh",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210478000,
            "customerNumber": "1-404",
            "firstName": "milonDeactivated",
            "lastName": "test8",
            "dateOfBirth": "2023-01-03",
            "email": "test@example.com",
            "gender": "FEMALE",
            "street": "terlkjeslieslirt",
            "houseNumber": null,
            "zipCode": "7678897867678",
            "city": "ffgfghhjh",
            "country": "BI",
            "status": "MEMBER",
            "cardNumbers": [
                "257"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210478002,
            "customerNumber": "1-406",
            "firstName": "milon",
            "lastName": "test11",
            "dateOfBirth": "2023-01-02",
            "email": null,
            "gender": "FEMALE",
            "street": "jkhzgfkgthz",
            "houseNumber": null,
            "zipCode": "66666",
            "city": "hjhgj",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210478220,
            "customerNumber": "1-405",
            "firstName": "milon",
            "lastName": "test9",
            "dateOfBirth": "2023-01-05",
            "email": null,
            "gender": "FEMALE",
            "street": "xcvsd",
            "houseNumber": null,
            "zipCode": "rtr",
            "city": "xcghbdfgh",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210478221,
            "customerNumber": "1-407",
            "firstName": "card",
            "lastName": "test10",
            "dateOfBirth": "2001-12-11",
            "email": null,
            "gender": "MALE",
            "street": "mystr",
            "houseNumber": "6",
            "zipCode": "zgzz",
            "city": "rrerrtret",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/53392768-4049-49ad-8721-e8a24dfe59c5.jpg?Expires=1683622800&Signature=jDqpJaIHa4786uY1wMd82NPK1-qCuLUPqNANOXJMvbjJBOvLILAikz05ABoTVlORbtjDDWp8hCyzygeMfzwTU1SbMVgQi0n3TkWg1xkphIFCejuTu6q5YRWcJj9CtfAi7TTs85bIHzHb6dWKfLC3ugMybqvtfolqz7fUFxlH-MtJX01Y3INb5MyAb4QqQp9zfXArQVsgZC-9tp45WCZPGwPG5SqJpqodna3qxgikwZSsy2YXs52Mx3it29QjMOl544rYXHWkdaLWiUe68buhEmTKcK2wIT0WheQLamVS2vLYTiKMr3hoc2jaK96DfPnTuSaDSi8-ZA3MgPpSLD6rsQ__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "333334",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210478790,
            "customerNumber": "1-409",
            "firstName": "Annelie",
            "lastName": "Brehm",
            "dateOfBirth": "1982-01-24",
            "email": "annelie.brehm+ml@egym.com",
            "gender": "FEMALE",
            "street": "Einsteinstr",
            "houseNumber": "192",
            "zipCode": "81699",
            "city": "München",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210492050,
            "customerNumber": "1-410",
            "firstName": "Heartrate",
            "lastName": "Milon",
            "dateOfBirth": "1986-10-03",
            "email": null,
            "gender": "MALE",
            "street": "Heartratestreet",
            "houseNumber": "154",
            "zipCode": "45632",
            "city": "Heartrate City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210510200,
            "customerNumber": "1-412",
            "firstName": "Simon",
            "lastName": "Test-Member-RFID",
            "dateOfBirth": "1989-03-01",
            "email": "TestMemberRFID@egym.com",
            "gender": "MALE",
            "street": "RFID Street",
            "houseNumber": "1",
            "zipCode": "12345",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "3983270084"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210514403,
            "customerNumber": "1-415",
            "firstName": "Addon",
            "lastName": "FutureML",
            "dateOfBirth": "1989-02-23",
            "email": "futureaddon@egym.com",
            "gender": "FEMALE",
            "street": "addonstr",
            "houseNumber": "1",
            "zipCode": "78643",
            "city": "Citystreet1",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210514651,
            "customerNumber": "1-414",
            "firstName": "Future",
            "lastName": "Ary",
            "dateOfBirth": "1990-02-07",
            "email": "futurestreet1@egym.com",
            "gender": "FEMALE",
            "street": "Futurestreet",
            "houseNumber": "1",
            "zipCode": "76734",
            "city": "Futurecity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210536831,
            "customerNumber": "1-416",
            "firstName": "Gnädinger",
            "lastName": "Dennis",
            "dateOfBirth": "1986-11-27",
            "email": null,
            "gender": "MALE",
            "street": "Hammer Steindamm",
            "houseNumber": "3-25",
            "zipCode": "22089",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "349B0675"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210541730,
            "customerNumber": "1-418",
            "firstName": "Milon",
            "lastName": "ImageTest",
            "dateOfBirth": "1993-10-16",
            "email": null,
            "gender": "MALE",
            "street": "imagestreet",
            "houseNumber": "42",
            "zipCode": "12348",
            "city": "Imagehausen",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/f9af62ef-8826-40c7-9154-e2556517bcac.jpg?Expires=1683622800&Signature=JVAvk8iRlfnmUUONJ7nqxhiInRzfiZQRyRu994L2n6kD2~9PyTcDo6JQfORXOaR~LUcKgLTok14JhxCYadwvLsNbeYrZMYtF4jpL5H7MqdQj-ZX~FfMLTaDlyYBG4nZ9V-9fLe~M22IKBv0Xsj6BOFoGhMyeM2qtaJ3KOD6wUPd5DXITJSOLpzctNy3~Fa2gqIFbEqO2m1hieRCVWcen6t06mlfWBnytSTValv~SkwjX8MwZzmUUb8-35mi8lAFsqYwxY0X-jnk-43rjY51G6WAUcljxX-eNrGuyUWUnyFWu-XFgKuUuBB21-ACMMkT2hbq4-t5QxOjua3fJeKCpOw__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210556522,
            "customerNumber": "1-419",
            "firstName": "Fedosieieva",
            "lastName": "Inna",
            "dateOfBirth": "2000-02-10",
            "email": null,
            "gender": "FEMALE",
            "street": "Alonso Heredia 11",
            "houseNumber": null,
            "zipCode": "28028",
            "city": "Madrid",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": {
                "accountHolder": "Fedosieieva Inna",
                "bankName": "BARCLAYS BANK UK PLC",
                "bic": "BUKBGB22XXX",
                "iban": "GB33BUKB20201555555555"
            }
        },
        {
            "id": 1210559190,
            "customerNumber": "1-420",
            "firstName": "Milon",
            "lastName": "Prospect5",
            "dateOfBirth": "1987-12-07",
            "email": null,
            "gender": "FEMALE",
            "street": "Prospectstreet",
            "houseNumber": "123",
            "zipCode": "45673",
            "city": "Prospect City",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210568370,
            "customerNumber": "1-422",
            "firstName": "Test40",
            "lastName": "Dmytro",
            "dateOfBirth": "2001-02-08",
            "email": "dmytro.kononiuk+mltest40@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210568371,
            "customerNumber": "1-423",
            "firstName": "Test41",
            "lastName": "Dmytro",
            "dateOfBirth": "2000-02-21",
            "email": "dmytro.kononiuk+mltest41@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210571450,
            "customerNumber": "1-424",
            "firstName": "Dmitry",
            "lastName": "Kovalenko",
            "dateOfBirth": "2000-11-03",
            "email": "dmitry.kovalenko+0103@egym.com",
            "gender": "MALE",
            "street": "Street 1",
            "houseNumber": "1",
            "zipCode": "1235",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210571780,
            "customerNumber": "1-425",
            "firstName": "Dima",
            "lastName": "Kovalenko",
            "dateOfBirth": "2000-03-02",
            "email": "dmitry.kovalenko+999@egym.com",
            "gender": "MALE",
            "street": "Str1",
            "houseNumber": "1",
            "zipCode": "1245",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "8928223"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210571781,
            "customerNumber": "1-426",
            "firstName": "Tester",
            "lastName": "Erik",
            "dateOfBirth": "1984-03-22",
            "email": "nicolas.festl+milon@sportalliance.com",
            "gender": "MALE",
            "street": "Strasse",
            "houseNumber": "123",
            "zipCode": "14425",
            "city": "Stadt",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": "https://assets.magicline.com/open-api-demo/customer-image/c1f2b50b-30e1-4c6f-bc72-29d8c23ea3ef.jpg?Expires=1683622800&Signature=j-rKadOK64wA3WGfih~xBJvdTCEC8wGL11Y4G0DC5j4U-S08K9HVWqLgghajJDw5K-BD~FJ4b9KxT7Bn~uU3OTWrnk5OklJztbFxUnJsxC6yFSfhCnO6zrHSPnr6--2eilAQ0Ed0ETSYdkgSaHRdHrnWPoVyvXcLt-qD9~kb8RmPAT0PihaCaI5hmqOdxINN7YwzyHFAD9UHRyt5BhTV2ggSpV6JHVCuM~TSUTnTunZR2GSUrIUVgYhn3qZen7qXYhjddS84dxUuzHgx3dljgNdA2eXZRgkSp6R36MUZ1uw-r5HSHwUi28D46VL5EA~45dpx5avKwxbPyX~wU6DpKQ__&Key-Pair-Id=APKAIYMEPHHS7SD645SQ",
            "phonePrivate": "056225695",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210577151,
            "customerNumber": "1-427",
            "firstName": "Giorgio",
            "lastName": "Bertero",
            "dateOfBirth": "1969-07-01",
            "email": "gbertero@technogym.com",
            "gender": "MALE",
            "street": "Via Calcinaro",
            "houseNumber": "2861",
            "zipCode": "47521",
            "city": "Cesena",
            "country": "IT",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": "+393456476287",
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210586290,
            "customerNumber": "1-434",
            "firstName": "ProductML",
            "lastName": "ML test",
            "dateOfBirth": "2000-03-17",
            "email": "productegym+ml@egym.com",
            "gender": "FEMALE",
            "street": "Street test",
            "houseNumber": "1",
            "zipCode": "56734",
            "city": "City test",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210590201,
            "customerNumber": "1-436",
            "firstName": "Dmytro",
            "lastName": "Test42",
            "dateOfBirth": "2000-03-03",
            "email": "dmytro.kononiuk+mltest42@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210591521,
            "customerNumber": "1-438",
            "firstName": "Testnew",
            "lastName": "MLNew",
            "dateOfBirth": "1989-04-21",
            "email": "newml@egym.com",
            "gender": "FEMALE",
            "street": "Boeckelstr",
            "houseNumber": "2",
            "zipCode": "65784",
            "city": "Citytest",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210591610,
            "customerNumber": "1-437",
            "firstName": "ProductML",
            "lastName": "Futuretest",
            "dateOfBirth": "1987-03-28",
            "email": "productfuture@egym.com",
            "gender": "UNISEX",
            "street": "Teststreet",
            "houseNumber": "1",
            "zipCode": "78654",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210594300,
            "customerNumber": "1-439",
            "firstName": "WolfeschlegelsteinhausenbergerdorffWolfeschlegelsteinhausenbergerrrrrsdcdsyyhgfd",
            "lastName": "WolfeschlegelsteinhausenbergerdorffWolfeschlegelsteinhausenbergerrrrrsdcdsyyhgfd",
            "dateOfBirth": "1990-03-08",
            "email": null,
            "gender": "UNISEX",
            "street": "q",
            "houseNumber": null,
            "zipCode": "fd",
            "city": "n",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210598130,
            "customerNumber": "1-440",
            "firstName": "Dmytro",
            "lastName": "Test43",
            "dateOfBirth": "2000-03-03",
            "email": "dmytro.kononiuk+mltest43@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1234321"
            ],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210601601,
            "customerNumber": "1-441",
            "firstName": "Product",
            "lastName": "FutureML",
            "dateOfBirth": "1987-04-17",
            "email": "mlfakeemail@egymail.com",
            "gender": "FEMALE",
            "street": "Test street",
            "houseNumber": "1",
            "zipCode": "56478",
            "city": "Cologne",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210601771,
            "customerNumber": "1-442",
            "firstName": "Addon",
            "lastName": "TestML",
            "dateOfBirth": "1989-05-26",
            "email": "addontestml@egym.com",
            "gender": "FEMALE",
            "street": "Streettest",
            "houseNumber": "2",
            "zipCode": "56457",
            "city": "Testcity",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210607371,
            "customerNumber": "1-443",
            "firstName": "Ko1",
            "lastName": "Dim1",
            "dateOfBirth": "2000-03-13",
            "email": "dkovalenko8744@gmail.com",
            "gender": "MALE",
            "street": "dvdv",
            "houseNumber": null,
            "zipCode": "223",
            "city": "dv",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210620570,
            "customerNumber": "1-445",
            "firstName": "secaseca",
            "lastName": "test",
            "dateOfBirth": "1994-12-14",
            "email": null,
            "gender": "UNISEX",
            "street": "test",
            "houseNumber": null,
            "zipCode": "test",
            "city": "test",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210634890,
            "customerNumber": "1-447",
            "firstName": "Collazos",
            "lastName": "sergio",
            "dateOfBirth": "2001-03-07",
            "email": "sergio.collazos+mltest@egym.com",
            "gender": "MALE",
            "street": "hhhhhstr",
            "houseNumber": "23",
            "zipCode": "81669",
            "city": "münchen",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210649621,
            "customerNumber": "1-451",
            "firstName": "Milon",
            "lastName": "JsonTesting",
            "dateOfBirth": "2000-03-08",
            "email": null,
            "gender": "MALE",
            "street": "Teststreet",
            "houseNumber": "3",
            "zipCode": "86154",
            "city": "Augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210649622,
            "customerNumber": "1-452",
            "firstName": "Buddy",
            "lastName": "Test",
            "dateOfBirth": "1999-11-11",
            "email": null,
            "gender": "FEMALE",
            "street": "Buddystreet",
            "houseNumber": "42",
            "zipCode": "98732",
            "city": "Hof",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210651750,
            "customerNumber": "1-453",
            "firstName": "Create",
            "lastName": "milon",
            "dateOfBirth": "1999-11-11",
            "email": "citymore@gmail.com",
            "gender": "MALE",
            "street": "Test",
            "houseNumber": "3",
            "zipCode": "84372",
            "city": "augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210651751,
            "customerNumber": "1-454",
            "firstName": "Test3",
            "lastName": "Milon",
            "dateOfBirth": "1999-12-11",
            "email": null,
            "gender": "FEMALE",
            "street": "Andreas",
            "houseNumber": "3",
            "zipCode": "37392",
            "city": "Martin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210652241,
            "customerNumber": "1-455",
            "firstName": "Test",
            "lastName": "User",
            "dateOfBirth": "1999-12-12",
            "email": "citymore@gmail.com",
            "gender": "FEMALE",
            "street": "testing",
            "houseNumber": "2",
            "zipCode": "28383",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210676461,
            "customerNumber": "1-458",
            "firstName": "EGYM+",
            "lastName": "ProductML",
            "dateOfBirth": "1987-04-16",
            "email": "productegym+@egym.com",
            "gender": "FEMALE",
            "street": "Teststr",
            "houseNumber": "1",
            "zipCode": "67502",
            "city": "Hamburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210676610,
            "customerNumber": "1-457",
            "firstName": "Test",
            "lastName": "Doe",
            "dateOfBirth": "2001-04-26",
            "email": "doe+egym+@egym.com",
            "gender": "FEMALE",
            "street": "Doestr",
            "houseNumber": "1",
            "zipCode": "87935",
            "city": "Augsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210677662,
            "customerNumber": "1-459",
            "firstName": "Premium",
            "lastName": "Egym",
            "dateOfBirth": "2000-04-29",
            "email": "premiumandbasic@egym.com",
            "gender": "FEMALE",
            "street": "Teststrasse",
            "houseNumber": "2",
            "zipCode": "34567",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210683750,
            "customerNumber": "1-460",
            "firstName": "Dmytro",
            "lastName": "Test44",
            "dateOfBirth": "2000-04-05",
            "email": "dmytro.kononiuk+mltest44@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210691011,
            "customerNumber": "1-462",
            "firstName": "Test18043",
            "lastName": "Dmytro",
            "dateOfBirth": "2000-04-05",
            "email": "dmytro.kononiuk+conn1804@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210691013,
            "customerNumber": "1-463",
            "firstName": "Test18042",
            "lastName": "Dmytro",
            "dateOfBirth": "2000-04-05",
            "email": "dmytro.kononiuk+conn1804_1@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210697960,
            "customerNumber": "1-465",
            "firstName": "Graf",
            "lastName": "Maga",
            "dateOfBirth": "1980-04-01",
            "email": null,
            "gender": "MALE",
            "street": "Bahnstr.",
            "houseNumber": "11",
            "zipCode": "12345",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [
                "1360178334208144"
            ],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210711490,
            "customerNumber": "1-466",
            "firstName": "Demo",
            "lastName": "Test",
            "dateOfBirth": "2000-04-14",
            "email": "mldemotest@mailinator.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210718332,
            "customerNumber": "1-469",
            "firstName": "Test",
            "lastName": "Tetiana",
            "dateOfBirth": "1990-04-04",
            "email": "test_ml_member@mailinator.com",
            "gender": "FEMALE",
            "street": "dfv",
            "houseNumber": "3",
            "zipCode": "23",
            "city": "dav",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210731621,
            "customerNumber": "1-470",
            "firstName": "Florian",
            "lastName": "Haegele",
            "dateOfBirth": "1989-04-21",
            "email": "fhaegele@technogym.com",
            "gender": "UNISEX",
            "street": "Schwabenstraße",
            "houseNumber": "3",
            "zipCode": "71636",
            "city": "Ludwigsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210735330,
            "customerNumber": "1-471",
            "firstName": "Sascha",
            "lastName": "Peter",
            "dateOfBirth": "1999-11-11",
            "email": "speter@technogym.com",
            "gender": "MALE",
            "street": "211",
            "houseNumber": null,
            "zipCode": "63263",
            "city": "Neu-Isenburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "+491742400453",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210737670,
            "customerNumber": "1-472",
            "firstName": "Tetiana 2",
            "lastName": "Test",
            "dateOfBirth": "1990-04-04",
            "email": "test_ml_member_1@mailinator.com",
            "gender": "MALE",
            "street": "df",
            "houseNumber": null,
            "zipCode": "dfb",
            "city": "dfb",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210742011,
            "customerNumber": "1-474",
            "firstName": "Mlmms1",
            "lastName": "testmms",
            "dateOfBirth": "2000-04-04",
            "email": "mmstestproduct@egym.com",
            "gender": "FEMALE",
            "street": "einbastr",
            "houseNumber": "1",
            "zipCode": "7685",
            "city": "Berlin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210742190,
            "customerNumber": "1-473",
            "firstName": "ML",
            "lastName": "testpremium",
            "dateOfBirth": "2000-04-22",
            "email": "testpremium@egym.com",
            "gender": "FEMALE",
            "street": "teststr",
            "houseNumber": "1",
            "zipCode": "87687",
            "city": "München",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210743150,
            "customerNumber": "1-475",
            "firstName": "mmstest1",
            "lastName": "Ary",
            "dateOfBirth": "1990-04-13",
            "email": "mmstary@egym.com",
            "gender": "FEMALE",
            "street": "allestr",
            "houseNumber": "4",
            "zipCode": "76840",
            "city": "AUgsburg",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210743970,
            "customerNumber": "1-476",
            "firstName": "test",
            "lastName": "aryaddon",
            "dateOfBirth": "1987-04-25",
            "email": "arytestaddon@egym.com",
            "gender": "FEMALE",
            "street": "teststr",
            "houseNumber": "7",
            "zipCode": "89674",
            "city": "München",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210760310,
            "customerNumber": "1-477",
            "firstName": "Dmytro",
            "lastName": "Test46",
            "dateOfBirth": "2000-04-28",
            "email": "dmytro.kononiuk+mltest46@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210772360,
            "customerNumber": "1-498",
            "firstName": "Push",
            "lastName": "Test",
            "dateOfBirth": "1990-04-04",
            "email": "test_push@mailinator.com",
            "gender": "MALE",
            "street": "efg",
            "houseNumber": null,
            "zipCode": "345",
            "city": "df",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210780620,
            "customerNumber": "1-579",
            "firstName": "Dmytro",
            "lastName": "Test47",
            "dateOfBirth": "2000-05-04",
            "email": "dmytro.kononiuk+mltest47@egym.com",
            "gender": "MALE",
            "street": "add2",
            "houseNumber": null,
            "zipCode": "2322",
            "city": "Vin",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "234242",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210785220,
            "customerNumber": "1-581",
            "firstName": "julius",
            "lastName": "sportsmand",
            "dateOfBirth": "1980-01-01",
            "email": "julius@innovatise.com",
            "gender": "MALE",
            "street": "zxcxz",
            "houseNumber": null,
            "zipCode": "xccxv",
            "city": "xcvcx",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210786730,
            "customerNumber": "1-583",
            "firstName": "Kova3",
            "lastName": "Dimon",
            "dateOfBirth": "2000-01-01",
            "email": "dmitry.kovalenko+test3@egym.com",
            "gender": "MALE",
            "street": "Rev1",
            "houseNumber": null,
            "zipCode": "02068",
            "city": "Kyiv",
            "country": "UA",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": null,
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        },
        {
            "id": 1210794980,
            "customerNumber": "1-585",
            "firstName": "DuplicateEmail",
            "lastName": "Dmitry",
            "dateOfBirth": "2000-05-11",
            "email": "dmitry.kovalenko+demo@egym.com",
            "gender": "MALE",
            "street": "Rev",
            "houseNumber": null,
            "zipCode": "02068",
            "city": "Kyiv",
            "country": "DE",
            "status": "MEMBER",
            "cardNumbers": [],
            "imageUrl": null,
            "phonePrivate": "062223555",
            "phonePrivateMobile": null,
            "phoneBusiness": null,
            "phoneBusinessMobile": null,
            "bankAccount": null
        }
    ];
    // "hasNext": false,
    // "offset": "1210794980",
    // "lastOffsetId": 1210794980

    $arr_len = result.length;
    //console.log($arr_len)
for(var i=0; i<$arr_len; i++){
    console.log(result[i].id)
}
</script>